project:
  # Names
  name: Project Name
  groups:
    - group name
  # quotas
  quotas:
    nova:
      cores: 32
      instances: 10
      ram: 131072
    cinder:
      gigabytes: 2048
      volumes: 20
      snapshots: 20
    neutron:
      network: 4
      subnet: 8
      port: 50
      router: 2
      security_group: 10
      security_group_rule: 10
      floatingip: 10
  flavors:
    - hpc.2c.2r.10h
    - hpc.2c.4r.10h
    - hpc.4c.2r.10h
    - hpc.4c.4r.10h
